language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: us-east-1
  app: micro-frontends
  env: user
  bucket_name: microfrontends
  on:
    branch: master
    repo: vuza/micro-frontends-user

notifications:
  email: false
